import { createBrowserRouter, RouterProvider } from "react-router-dom"
import Home from "./routes/Home/index.jsx"
import Produtos from "./routes/Produtos/index.jsx"
import Error from "./routes/Error/index.jsx"
import EditarProduos from "./routes/EditarProdutos//index.jsx"